
/* For APIs */

export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';


export const INFO_LOADING = 'INFO_LOADING';
export const ALL_CATEGORIES_LOADING = 'ALL_CATEGORIES_LOADING';
export const SPECIFIC_CATEGORIES_LOADING = 'SPECIFIC_CATEGORIES_LOADING';
export const REVIEWS_LOADING = 'REVIEWS_LOADING';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_SPECIFIC_CATEGORIES = 'GET_SPECIFIC_CATEGORIES';
export const GET_PLACES = 'GET_PLACES';
export const GET_SPECIFIC_PLACE = 'GET_SPECIFIC_PLACE';
export const GET_REVIEWS = 'GET_REVIEWS';

/* For components */

export const DISPLAY_NAVBAR = 'DISPLAY_NAVBAR';
export const HIDE_NAVBAR = 'HIDE_NAVBAR';
