/* For auth */

export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

/* Adding and removing favourites */
export const FAVOURITE_ADDED = 'FAVOURITE_ADDED'
export const FAVOURITE_REMOVED = 'FAVOURITE_REMOVED'

/* For APIs */

// AirVisual
export const WEATHER_LOADING = 'WEATHER_LOADING'
export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER'

// Yelp
export const INFO_LOADING = 'INFO_LOADING'
export const ALL_CATEGORIES_LOADING = 'ALL_CATEGORIES_LOADING'
export const SPECIFIC_CATEGORIES_LOADING = 'SPECIFIC_CATEGORIES_LOADING'
export const REVIEWS_LOADING = 'REVIEWS_LOADING'
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
export const GET_SPECIFIC_CATEGORIES = 'GET_SPECIFIC_CATEGORIES'
export const GET_PLACES = 'GET_PLACES'
export const GET_SPECIFIC_PLACE = 'GET_SPECIFIC_PLACE'
export const GET_REVIEWS = 'GET_REVIEWS'
export const LOADING_ERROR = 'LOADING_ERROR'

/* For components */

export const DISPLAY_NAVBAR = 'DISPLAY_NAVBAR'
export const HIDE_NAVBAR = 'HIDE_NAVBAR'
